---
- hosts: webserver
  become: yes
  tasks:
  - name: i want to install java on ubuntu ansible nodes
    apt:
     name: "{{javaubuntu}}"
     state: present
    when: ansible_os_family =="Debian"

  - name: i want to install java on redhat ansible nodes
    yum:
     name: "{{javaredhat}}"
     state: present
    when: ansible_os_family =="RedHat"
