---
- hosts: webserver
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu ansible nodes
    apt:
     name: apache2
     state: present
    when: ansible_os_family =="Debian"
  - name: i want to start my webserver on nodes by using ubuntu
    service:
     name: apache2
     state: started
    when: ansible_os_family =="Debian"

  - name: i want to install webserver on redhat ansible nodes
    yum:
     name: httpd
     state: present
    when: ansible_os_family =="RedHat"
  - name: i want to start my webserver on nodes by using redhat
    service:
     name: httpd
     state: started
    when: ansible_os_family =="RedHat"